/// <reference path="../typings/tsd.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/asset.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../scenes/startscene.ts"/>
/// <reference path="../scenes/intro.ts" />
/// <reference path="../scenes/insidemansion.ts" />
/// <reference path="../scenes/ground.ts" />
/// <reference path="../scenes/takeknife.ts" />
/// <reference path="../scenes/groundrun.ts" />
/// <reference path="../scenes/upstairs.ts" />
/// <reference path="../scenes/upstairsright.ts" />
/// <reference path="../scenes/upstairsleft.ts" />
/// <reference path="../scenes/outside.ts" />
/// <reference path="../scenes/followroad.ts" />
/// <reference path="../scenes/zombiecar.ts" />
/// <reference path="../scenes/ignorecar.ts" />
/// <reference path="../scenes/forest.ts" />
/// <reference path="../scenes/cave.ts" />
/// <reference path="../scenes/light.ts" />
//# sourceMappingURL=_reference.js.map